// ITA Division I Women's Doubles Rankings - Year-End 2025-26 (May 20, 2026)
// Source: https://colleges.wearecollegetennis.com/rankings
// Keys: lowercase player name. Doubles is a team ranking — each player
// on a team gets the same rank. Some players appear on multiple ranked
// teams; the lookup should return their BEST (lowest #) rank.

const ITA_DOUBLES_W = {
  "roisin gilheany": 1,
  "gloriana nahum": 1,
  "gabriella broadfoot": 2,
  "victoria osuigwe": 2,
  "ava esposito": 3,
  "dj bennett": 3,
  "reese brantmeier": 4,
  "alanis hamilton": 4,
  "deniz dilek": 5,
  "aysegul mert": 5,
  "anastasiia lopata": 6,
  "patricija paukstyte": 6,
  "angella okutoyi": 7,
  "merna refaat": 7,
  "flora johnson": 8,
  "luciana perry": 8,
  "melodie collard": 9,
  "vivian yang": 9,
  "ange oby kajuru": 10,
  "susanna maltby": 10,
  "sophia webster": 11,
  "celia-belle mohr": 11,
  "lucciana perez": 12,
  "mia kupres": 12,
  "ziva falkner": 13,
  "sonja zhiyenbayeva": 13,
  "andrea nova": 14,
  "emily welker": 14,
  "lauren friedman": 15,
  "helena buchwald": 15,
  "amelie van impe": 16,
  "caroline mcginley": 16,
  "valeria ray": 17,
  "bridget stammel": 17,
  "ella mcdonald": 18,
  "kenna erickson": 18,
  "anet koskel": 19,
  "carolina gomez alonso": 19,
  "nikola daubnerova": 20,
  "xinyi nong": 20,
  "charlotte kempenaers-pocz": 21,
  "chiara di genova": 21,
  "lily jones": 22,
  "jessica bernales": 22,
  "annabelle xu": 23,
  "martina genis salas": 23,
  "krisha mahendran": 24,
  "lily fairclough": 24,
  "olivia center": 25,
  "kate fakih": 25,
  "evialina laskevich": 26,
  "edda mamedova": 26,
  "kayla cross": 27,
  "margot phanthala": 28,
  "erica jessel": 28,
  "catherine aulia": 29,
  "leyla britez risso": 29,
  "cadence brace": 30,
  "maria sholokhova": 31,
  "lucie urbanova": 31,
  "anastasiya komar": 32,
  "rose marie nijkamp": 32,
  "diya challa": 33,
  "emma ghirardato": 33,
  "hephzibah oluwadare": 34,
  "teah chavez": 34,
  "salma drugdova": 35,
  "anastasia abbagnato": 35,
  "francesca mattioli": 36,
  "vanesa suarez": 36,
  "matilde morais": 37,
  "ellie blackford": 37,
  "sara suchankova": 38,
  "ni xi": 38,
  "katie spencer": 39,
  "conley raidt": 39,
  "elizabeth ionescu": 40,
  "chantal sauvant": 41,
  "anastasiia grechkina": 41,
  "athina pitta": 42,
  "gianna oboniye": 42,
  "anna zyryanova": 43,
  "jasmine conway": 43,
  "valery gynina": 44,
  "brooke black": 44,
  "hiilani williams": 45,
  "alessandra teodosescu": 45,
  "bianca molnar": 46,
  "bojana pozder": 46,
  "ilinca amariei": 47,
  "violeta martinez": 47,
  "shavit kimchi": 49,
  "liv hovde": 49,
  "giorgia roselli": 50,
  "xin tong wang": 50,
  "arina gamretkaia": 51,
  "ozlem uslu": 51,
  "alice xu": 52,
  "tess bucher": 52,
  "angella okutoyi": 7,
  "ava esposito": 3,
  "yekaterina dmitrichenko": 54,
  "hailey murphy": 54,
  "eleana yu": 55,
  "claire an": 55,
  "kavya karra": 56,
  "stephanie yakoff": 56,
  "laura rahnel": 57,
  "reese miller": 57,
  "ece gencer": 58,
  "ida clement": 58,
  "daniela borruel": 59,
  "jade groen": 60,
  "rinon okuwaki": 60,
  "mai nguyen": 61,
  "zuzanna frankowska": 61,
  "christasha mcneil": 62,
  "maelie monfils": 63,
  "olivia dorner": 63,
  "ellison reynoldson": 64,
  "ekaterina ivanova": 64,
  "lillie murphy": 65,
  "elle warren": 65,
  "jo-yee chan": 66,
  "vessa turley": 66,
  "alexia jacobs": 67,
  "anna-marie weissheim": 67,
  "ema kovacevic": 68,
  "uma bakaityte": 69,
  "darya schwartzman": 69,
  "asuncion jadue": 70,
  "reese sager": 70,
  "anne-christine lutkemeyer": 71,
  "mayu crossley": 71,
  "gabriella rawles": 72,
  "rylie hanford": 72,
  "daianne hayashida": 73,
  "mia mack": 73,
  "tianmei wang": 74,
  "alyssa ahn": 74,
  "jana hossam salah": 75,
  "anastasiia gureva": 85,
  "neena feldman": 78,
  "marelie raath": 78,
  "panna bartha": 79,
  "katrin pavkova": 79,
  "nevena carton": 80,
  "kady tannenbaum": 80,
  "silvia pomarolli": 81,
  "vittoria benedetti": 81,
  "tilde jagare": 83,
  "olivia symons": 83,
  "carina syrtveit": 84,
  "romana cisovska": 86,
  "gaia parravicini": 86,
  "mika dagan fruchtman": 87,
  "alice soulie": 88,
  "riley crowder": 88,
  "kaitlyn carnicella": 89,
  "anna bella bianca bergqvist larsson": 89,
  "clara owen": 90,
  "abby nugent": 90
};
