// ITA Division I Men's Doubles Rankings - Year-End 2025-26 (May 20, 2026)
// Source: https://colleges.wearecollegetennis.com/rankings
// Keys: lowercase player name. Doubles is a team ranking — each of the
// two players on a team gets the same rank. If a player appears on
// multiple ranked teams, the lookup should return their BEST (lowest #) rank.

const ITA_DOUBLES_M = {
  "dhakshineswar suresh": 1,
  "andrew delgado": 1,
  "theo papamalamis": 2,
  "togan tokac": 2,
  "cosme rolland de ravel": 3,
  "duncan chan": 3,
  "bruno nhavene": 4,
  "luis carlos alvarez valdes": 4,
  "arda azkara": 5,
  "santiago giamichelle": 5,
  "brandon carpico": 6,
  "nikita filin": 6,
  "paul barbier gazeu": 7,
  "lucas andrade da silva": 7,
  "benito sanchez martinez": 8,
  "petar jovanovic": 8,
  "mans dahlberg": 9,
  "dylan dietrich": 9,
  "billy blaydes": 10,
  "freddy blaydes": 10,
  "andrii zimnokh": 11,
  "vit kalina": 11,
  "nathan cox": 12,
  "hoyoung roh": 12,
  "tanapatt nirundorn": 13,
  "henry jefferson": 13,
  "pedro rodenas": 14,
  "cooper williams": 14,
  "eli stephenson": 15,
  "jack loutit": 15,
  "andrej loncarevic": 16,
  "sasa markovic": 16,
  "stiles brockett": 17,
  "filip gustafsson": 18,
  "glib sekachov": 18,
  "martin borisiouk": 19,
  "jules leroux": 19,
  "noa vukadin": 20,
  "viktor markov": 20,
  "lucas marionneau": 21,
  "sebastian gorzny": 21,
  "luis felipe miguel": 22,
  "erik schiessl": 22,
  "anthony wright": 23,
  "roan jones": 23,
  "alex chang": 24,
  "alexander razeghi": 24,
  "cooper woestendick": 25,
  "albert pedrico kravtsov": 25,
  "michal novansky": 26,
  "manfredi graziani": 27,
  "aaron sandler": 27,
  "eric padgham": 28,
  "ben weintraub": 28,
  "max dahlin": 29,
  "bjorn swenson": 29,
  "isac stromberg": 30,
  "kai milburn": 30,
  "paul inchauspe": 31,
  "landon ardila": 31,
  "taym alazmeh": 32,
  "danial rakhmatullayev": 32,
  "matteo antonescu": 33,
  "michael andre": 33,
  "carter pate": 34,
  "greyson casey": 34,
  "spencer johnson": 35,
  "emon van loben sels": 35,
  "nathan trouve": 36,
  "maxwell exsted": 36,
  "alexander aney": 37,
  "timofey stepanov": 37,
  "adrien berrut": 38,
  "lambert ruland": 38,
  "mehdi sadaoui": 39,
  "jakub kroslak": 39,
  "ozan baris": 40,
  "matthew forbes": 40,
  "zsombor velcz": 41,
  "ioan alexandru chirita": 41,
  "alexander bernard": 42,
  "alex okonkwo": 42,
  "aidan kim": 43,
  "bryce nakashima": 43,
  "jay friend": 44,
  "sasha rozin": 44,
  "daniel phillips": 45,
  "lance nisbet": 45,
  "santiago navarro": 46,
  "petro kuzmenok": 46,
  "jacob olar": 47,
  "jan sebesta": 48,
  "rushil khosla": 49,
  "rethin pranav senthil kumar": 49,
  "sebastian eriksson": 50,
  "oliver ojakaar": 50,
  "kacper szymkowiak": 51,
  "mees rottgering": 51,
  "oscar lacides": 52,
  "alejandro melero": 52,
  "jangjun kim": 53,
  "cole stelse": 54,
  "alejandro arcila": 54,
  "thanaphat boosarawongse": 55,
  "aditya govila": 55,
  "trevor svajda": 56,
  "jerry barton": 56,
  "sebastian dominko": 57,
  "perry gregg": 57,
  "niksa arsic": 58,
  "thiago guglieri": 58,
  "luc koenig": 59,
  "connor henry van schalkwyk": 59,
  "luis llorens saracho": 60,
  "peter nad": 60,
  "william mroz": 61,
  "kenta miyoshi": 61,
  "sam landau": 62,
  "braeden gelletich": 62,
  "vojtech vales": 63,
  "shaurya bharadwaj": 63,
  "jip van assendelft": 64,
  "mateus ranciaro": 65,
  "joao pimenta": 65,
  "maximus dussault": 66,
  "oliver bonding": 66,
  "sturle hoff skigelstrand": 67,
  "kyle mcnally": 67,
  "luca bluett": 68,
  "john kim": 68,
  "kalin ivanovski": 69,
  "abel forger": 69,
  "martin vergara del puerto": 70,
  "oscar martinez": 70,
  "sean daryabeigi": 71,
  "max stenzer": 71,
  "marko mesarovic": 72,
  "henrik bladelius": 72,
  "manvydas balciunas": 73,
  "stian klaassen": 73,
  "charlie robertson": 74,
  "luca pow": 74,
  "connor smillie": 75,
  "jakub vrba": 75,
  "soham purohit": 76,
  "brett pearson": 76,
  "luciano alcocer": 77,
  "yeray andres pastor": 77,
  "aristotelis thanos": 78,
  "mitchell sheldon": 78,
  "blake hilsen": 79,
  "eyal shumilov": 79,
  "gianluca ballotta": 80,
  "tiago silva": 81,
  "rudy quan": 82,
  "aadarsh tripathi": 82,
  "wissam abderrahman": 83,
  "mehdi benchakroun": 83,
  "ondrej horak": 84,
  "karim al-amin": 84,
  "pierre mouesca": 85,
  "matthew burton": 85,
  "edward winter": 86,
  "david fix": 86,
  "aleksa krivokapic": 87,
  "maj premzl": 87,
  "calvin baierl": 88,
  "devin badenhorst": 88,
  "marcos castro fabra": 89,
  "sam reeve": 89,
  "miguel avendano cadena": 90,
  "lucca liu": 90
};
