// ITA Division I Women's Team Rankings - Year-End 2025-26 (May 20, 2026)
// Source: https://colleges.wearecollegetennis.com/rankings
// Keys MUST match the school strings used in transfers.js (newSchool / previousSchool).
// Schools not in this object are treated as unranked.

const ITA_RANKINGS_W = {
  "Texas A&M": 1,
  "Auburn": 2,
  "Georgia": 3,
  "Ohio State": 4,
  "UNC": 5,
  "Oklahoma": 6,
  "Virginia": 7,
  "NC State": 8,
  "Pepperdine": 9,
  "LSU": 10,
  "Texas": 11,
  "Michigan": 12,
  "USC": 13,
  "Duke": 14,
  "UCLA": 15,
  "Vanderbilt": 16,
  "Arizona State": 17,
  "Florida": 18,
  "Tennessee": 19,
  "UCF": 20,
  "TCU": 21,
  "Cal": 22,
  "Washington": 23,
  "SMU": 24,
  "Clemson": 25,
  "Miami (FL)": 26,
  "Texas Tech": 27,
  "Stanford": 28,
  "South Carolina": 29,
  "Wisconsin": 30,
  "Notre Dame": 31,
  "Charlotte": 32,
  "Arizona": 33,
  "Baylor": 34,
  "Wichita State": 35,
  "Maryland": 36,
  "Rice": 37,
  "Yale": 38,
  "BYU": 39,
  "Princeton": 40,
  "Kansas": 41,
  "Utah": 42,
  "Ole Miss": 43,
  "Oklahoma State": 44,
  "Houston": 45,
  "Columbia": 46,
  "Iowa": 47,
  "Illinois": 48,
  "North Florida": 49,
  "Nebraska": 50,
  "UC Santa Barbara": 51,
  "San Diego State": 52,
  "San Diego": 53,
  "Arkansas": 54,
  "Alabama": 55,
  "Penn State": 56,
  "Mississippi State": 57,
  "Old Dominion": 58,
  "Wake Forest": 59,
  "Northwestern": 60,
  "Harvard": 61,
  "Brown": 62,
  "Dartmouth": 63,
  "Boston College": 64,
  "Georgia Tech": 65,
  "Michigan State": 66,
  "Furman": 67,
  "Boise State": 68,
  "Denver": 69,
  "Indiana": 70,
  "UNLV": 71,
  "Oregon": 72,
  "Penn": 73,
  "FGCU": 74,
  "Colorado": 75
};
