// ITA Division I Men's Team Rankings - Year-End 2025-26 (May 20, 2026)
// Source: https://colleges.wearecollegetennis.com/rankings
// Keys MUST match the school strings used in transfers.js (newSchool / previousSchool).
// Schools not in this object are treated as unranked.

const ITA_RANKINGS_M = {
  "Virginia": 1,
  "Texas": 2,
  "Wake Forest": 3,
  "TCU": 4,
  "Ohio State": 5,
  "Mississippi State": 6,
  "Arizona": 7,
  "LSU": 8,
  "Oklahoma": 9,
  "Baylor": 10,
  "Texas A&M": 11,
  "Georgia": 12,
  "UCF": 13,
  "Illinois": 14,
  "South Carolina": 15,
  "Stanford": 16,
  "San Diego": 17,
  "Michigan State": 18,
  "UCLA": 19,
  "USC": 20,
  "Pepperdine": 21,
  "Florida": 22,
  "Vanderbilt": 23,
  "Notre Dame": 24,
  "Auburn": 25,
  "Cornell": 26,
  "Columbia": 27,
  "NC State": 28,
  "SMU": 29,
  "Clemson": 30,
  "Kentucky": 31,
  "Arizona State": 32,
  "Ole Miss": 33,
  "Wisconsin": 34,
  "Cal": 35,
  "UC Santa Barbara": 36,
  "Princeton": 37,
  "Santa Clara": 38,
  "UNC": 39,
  "Duke": 40,
  "Michigan": 41,
  "Arkansas": 42,
  "Miami (FL)": 43,
  "Penn": 44,
  "Yale": 45,
  "Oklahoma State": 46,
  "Harvard": 47,
  "Middle Tennessee": 48,
  "Florida State": 49,
  "Rice": 50,
  "Old Dominion": 51,
  "Charlotte": 52,
  "Utah State": 53,
  "Georgia Tech": 54,
  "Alabama": 55,
  "Tulsa": 56,
  "Nebraska": 57,
  "Oregon": 58,
  "Loyola Marymount": 59,
  "USF": 60,
  "Indiana": 61,
  "Louisville": 62,
  "Liberty": 63,
  "Tennessee": 64,
  "Memphis": 65,
  "Boise State": 66,
  "East Tennessee State": 67,
  "Wichita State": 68,
  "Northwestern": 69,
  "Grand Canyon": 70,
  "Virginia Tech": 71,
  "Samford": 72,
  "Texas Tech": 73,
  "UNLV": 74,
  "UC Irvine": 75
};
