// ITA Division I Men's Singles Rankings - Year-End 2025-26 (May 20, 2026)
// Source: https://colleges.wearecollegetennis.com/rankings
// Keys: lowercase full name (firstname lastname). Match against
// player.name from transfers.js (also lowercased).

const ITA_SINGLES_M = {
  "dylan dietrich": 1,
  "sebastian gorzny": 2,
  "jay friend": 3,
  "trevor svajda": 4,
  "paul inchauspe": 5,
  "michael zheng": 6,
  "duncan chan": 7,
  "benito sanchez martinez": 8,
  "max dahlin": 9,
  "devin badenhorst": 10,
  "petar jovanovic": 11,
  "keegan rice": 12,
  "lucas andrade da silva": 13,
  "aidan kim": 14,
  "oliver tarvet": 15,
  "theo papamalamis": 16,
  "kenta miyoshi": 17,
  "gabriel debru": 18,
  "matthew forbes": 19,
  "jakub vrba": 20,
  "william jansen": 21,
  "preston stearns": 22,
  "sebastian dominko": 23,
  "mees rottgering": 24,
  "vignesh gogineni": 25,
  "eli stephenson": 26,
  "jack anthrop": 27,
  "amirkhamza nasridinov": 28,
  "rodrigo fernandes": 29,
  "luis carlos alvarez valdes": 30,
  "kalin ivanovski": 31,
  "erik arutiunian": 32,
  "olaf pieczkowski": 33,
  "aristotelis thanos": 34,
  "luca pow": 35,
  "martin borisiouk": 36,
  "dhakshineswar suresh": 37,
  "sebastian eriksson": 38,
  "ozan baris": 39,
  "manfredi graziani": 40,
  "khololwam montsi": 41,
  "cosme rolland de ravel": 42,
  "cooper woestendick": 43,
  "emon van loben sels": 44,
  "alexander razeghi": 45,
  "arda azkara": 46,
  "nicolas kotzen": 47,
  "viktor markov": 48,
  "rohan murali": 49,
  "romain gales": 50,
  "bjorn swenson": 51,
  "alex okonkwo": 52,
  "connor henry van schalkwyk": 53,
  "zsombor velcz": 54,
  "spencer johnson": 55,
  "nicolas arseneault": 56,
  "cooper williams": 57,
  "andres santamarta roig": 58,
  "pedro rodenas": 59,
  "jangjun kim": 60,
  "pablo perez ramos": 61,
  "paul barbier gazeu": 62,
  "michael minasyan": 63,
  "petro kuzmenok": 64,
  "oscar lacides": 65,
  "yassine dlimi": 66,
  "sasha rozin": 67,
  "billy blaydes": 68,
  "dominique rolland": 69,
  "fryderyk lechno wasiutynski": 70,
  "mario martinez serrano": 71,
  "iker gaztambide arrastia": 72,
  "henry jefferson": 73,
  "stefano d'agostino": 74,
  "perry gregg": 75,
  "nathan trouve": 76,
  "sean daryabeigi": 77,
  "ilia snitari": 78,
  "orel kimhi": 79,
  "oliver ojakaar": 80,
  "nathan blokhin": 81,
  "filip gustafsson": 82,
  "william mroz": 83,
  "bor artnak": 84,
  "maxwell exsted": 85,
  "branko djuric": 86,
  "pablo martinez gomez": 87,
  "rudy quan": 88,
  "matic kriznik": 89,
  "nikita filin": 90,
  "roan jones": 91,
  "niccolo baroni": 92,
  "jack loutit": 93,
  "vit kalina": 94,
  "sachin palta": 95,
  "sam landau": 96,
  "hudson rivera": 97,
  "nacho serra sanchez": 98,
  "alexander frusina": 99,
  "lucca liu": 100,
  "bryce nakashima": 101,
  "timofey stepanov": 102,
  "manvydas balciunas": 103,
  "stian klaassen": 104,
  "bryan hernandez cortes": 105,
  "johan alexander rodriguez rodriguez": 106,
  "nour fathalla": 107,
  "vasco prata": 108,
  "andrej loncarevic": 109,
  "antonio prat": 110,
  "hoyoung roh": 111,
  "hugo car": 112,
  "jules leroux": 113,
  "zoran ludoski": 114,
  "andrii zimnokh": 115,
  "lasse poertner": 116,
  "matthieu chambonniere": 117,
  "abel forger": 118,
  "aryan shah": 119,
  "aleksa pisaric": 120,
  "joaquin guilleme": 121,
  "zaid mashni": 122,
  "azariah rusher": 123,
  "peter benjamin privara": 124,
  "william manning": 125
};
