// ITA Division I Women's Singles Rankings - Year-End 2025-26 (May 20, 2026)
// Source: https://colleges.wearecollegetennis.com/rankings
// Keys: lowercase full name (firstname lastname).
// Match against player.name from transfers.js (also lowercased).

const ITA_SINGLES_W = {
  "lucciana perez": 1,
  "reese brantmeier": 2,
  "carmen andreea herea": 3,
  "luciana perry": 4,
  "teah chavez": 5,
  "aysegul mert": 6,
  "ange oby kajuru": 7,
  "piper charney": 8,
  "irina balus": 9,
  "cadence brace": 10,
  "katrina scott": 11,
  "evialina laskevich": 12,
  "anastasia abbagnato": 13,
  "bridget stammel": 14,
  "anastasiia lopata": 15,
  "dj bennett": 16,
  "maria sholokhova": 17,
  "savannah dada-mascoll": 18,
  "lily jones": 19,
  "mia slama": 20,
  "ekaterina khayrutdinova": 21,
  "emily welker": 22,
  "annabelle xu": 23,
  "berta passola folch": 24,
  "jana hossam salah": 25,
  "anne-christine lutkemeyer": 26,
  "celia-belle mohr": 27,
  "amelie van impe": 28,
  "kayla cross": 29,
  "mia kupres": 30,
  "mayu crossley": 31,
  "carolina gomez alonso": 32,
  "valeria ray": 33,
  "emilija tverijonaite": 34,
  "anastasiia grechkina": 35,
  "valery gynina": 36,
  "valerie glozman": 37,
  "anna zyryanova": 38,
  "raquel gonzalez": 39,
  "monika ekstrand": 40,
  "ziva falkner": 41,
  "leyla britez risso": 42,
  "tatum evans": 43,
  "edda mamedova": 44,
  "kaitlyn carnicella": 45,
  "helena buchwald": 46,
  "sonja zhiyenbayeva": 47,
  "julia garcia ruiz": 48,
  "angella okutoyi": 49,
  "rose marie nijkamp": 50,
  "gabriella broadfoot": 51,
  "deniz dilek": 52,
  "johanne svendsen": 53,
  "india houghton": 54,
  "alyssa ahn": 55,
  "reece carter": 56,
  "gabia paskauskas": 57,
  "aspen schuman": 58,
  "mckenna schaefbauer": 59,
  "vivian yang": 60,
  "lavinia tanasie": 61,
  "ashton bowers": 62,
  "alejandra cruz": 63,
  "emma charney": 64,
  "ilinca amariei": 65,
  "eszter meri": 66,
  "ekaterina ivanova": 67,
  "sophia cisse-ignatiev": 68,
  "anastasiia gureva": 69,
  "na dong": 70,
  "nao nishino": 70,
  "rinon okuwaki": 72,
  "ella mcdonald": 73,
  "kyoka kubo": 74,
  "sophie llewellyn": 75,
  "mia mack": 76,
  "ava esposito": 77,
  "sofia rocchetti": 78,
  "zoe hammond": 79,
  "bianca molnar": 80,
  "raquel caballero chica": 81,
  "katie rolls": 82,
  "kristina paskauskas": 83,
  "reese miller": 84,
  "mao mushika": 85,
  "gian octa": 86,
  "erika matsuda": 87,
  "zuzanna kubacha": 88,
  "amara brahmbhatt": 89,
  "emma dong": 90,
  "stephanie yakoff": 91,
  "julia zhu": 92,
  "margot phanthala": 93,
  "vanesa suarez": 94,
  "liv hovde": 95,
  "yekaterina dmitrichenko": 96,
  "sofia rojas": 97,
  "eugenia zozaya menendez": 97,
  "lexington reed": 99,
  "eva alvarez sande": 100,
  "daria smetannikov": 101,
  "grace levelston": 102,
  "eva shaw": 103,
  "addison lanton": 104,
  "klara milicevic": 105,
  "emily sartz-lunde": 106,
  "emma kamper": 107,
  "maria de la paz alberto": 108,
  "jo-yee chan": 109,
  "isabelle lacy": 110,
  "lucie pawlak": 111,
  "kira matushkina": 112,
  "chantal sauvant": 113,
  "oliwia orlinska": 114,
  "olivia lincer": 115,
  "theodora chantava": 116,
  "alice ferlito": 117,
  "violeta martinez": 118,
  "hannah read": 119,
  "elizabeth ionescu": 120,
  "olivia benton": 121,
  "jantje tilbuerger": 122,
  "maxine murphy": 123,
  "laurie barendse": 124,
  "merna refaat": 125
};
