// transfers.js — THIS is the only file you edit to curate the tracker.
//
// To add a player: copy one { ... } block below, paste it at the top of the list,
// change the values, and make sure there's a comma after the closing } .
//
// Rules:
//   - status must be EXACTLY one of: "In Portal", "Committed", "Signed", "Withdrawn"
//   - leave newSchool as ""  until the player commits somewhere
//   - hometown is where the player is from, e.g. "Madrid, Spain" (leave "" if unknown)
//   - dateUpdated is NOT shown on the card anymore, but it still controls the order
//     (newest first), so keep setting it to the date you add or update someone
//   - give every player a unique id (just use the next number)

const TRANSFERS = [
  { id: "98", name: "Marcos Castro Fabra", status: "Signed", previousSchool: "Memphis", newSchool: "UC Santa Barbara", hometown: "Spain", country: "Spain", utr: "12.80", classYear: "Fr.", dateUpdated: "2026-05-27" },
  { id: "88", name: "Matthieu Chambonniere", status: "Committed", previousSchool: "Ole Miss", newSchool: "TCU", hometown: "France", country: "France", utr: "13.20", classYear: "", dateUpdated: "2026-05-27" },
  { id: "89", name: "Carson Baker", status: "Signed", previousSchool: "Boise State", newSchool: "Virginia Tech", hometown: "", country: "", utr: "12.66", classYear: "", dateUpdated: "2026-05-27" },
  { id: "90", name: "Théo Mottier", status: "Signed", previousSchool: "Weber State", newSchool: "VCU", hometown: "France", country: "France", utr: "12.17", classYear: "", dateUpdated: "2026-05-27" },
  { id: "91", name: "Mason Landreth", status: "Committed", previousSchool: "Louisiana-Lafayette", newSchool: "Ole Miss", hometown: "", country: "", utr: "12.61", classYear: "", dateUpdated: "2026-05-27" },
  { id: "92", name: "Tristan Berard", status: "Signed", previousSchool: "Grand Canyon", newSchool: "Arizona", hometown: "France", country: "France", utr: "13.00", classYear: "", dateUpdated: "2026-05-27" },
  { id: "93", name: "Mohammad Alkotop", status: "Signed", previousSchool: "Florida State", newSchool: "UCF", hometown: "Jordan", country: "Jordan", utr: "12.90", classYear: "", dateUpdated: "2026-05-27" },
  { id: "94", name: "Lincoln Battle", status: "Committed", previousSchool: "Cleveland State", newSchool: "Michigan State", hometown: "", country: "", utr: "12.64", classYear: "", dateUpdated: "2026-05-27" },
  { id: "95", name: "Rudy Ceccon", status: "Signed", previousSchool: "LSU", newSchool: "Arkansas", hometown: "France", country: "France", utr: "12.85", classYear: "", dateUpdated: "2026-05-27" },
  { id: "96", name: "Miguel Ángel Machado", status: "Committed", previousSchool: "Bryant", newSchool: "Texas Tech", hometown: "Spain", country: "Spain", utr: "12.49", classYear: "", dateUpdated: "2026-05-27" },
  { id: "97", name: "Timo de Visser", status: "Committed", previousSchool: "Jacksonville State", newSchool: "Idaho State", hometown: "Netherlands", country: "Netherlands", utr: "12.20", classYear: "", dateUpdated: "2026-05-27" },
  { id: "62", name: "Yazid Lahjomri", status: "In Portal", previousSchool: "UT Arlington", newSchool: "", hometown: "Rabat, Morocco", country: "Morocco", utr: "12.57", classYear: "Jr.", dateUpdated: "2026-05-27" },
  { id: "63", name: "Anirudh Nallaparaju", status: "In Portal", previousSchool: "Marist", newSchool: "", hometown: "Lyneham, Australia", country: "Australia", utr: "11.60", classYear: "So.", dateUpdated: "2026-05-27" },
  { id: "64", name: "Maxime Dubouch", status: "Signed", previousSchool: "Memphis", newSchool: "Georgia", hometown: "France", country: "France", utr: "13.17", classYear: "Gr.", dateUpdated: "2026-05-27" },
  { id: "65", name: "Boyd Schreiber", status: "Signed", previousSchool: "Gardner-Webb", newSchool: "Samford", hometown: "Australia", country: "Australia", utr: "12.04", classYear: "", dateUpdated: "2026-05-27" },
  { id: "66", name: "Jose David Segovia", status: "Signed", previousSchool: "Saint Leo", newSchool: "FAU", hometown: "Venezuela", country: "Venezuela", utr: "12.61", classYear: "So.", dateUpdated: "2026-05-27" },
  { id: "67", name: "Leo Galliano", status: "Committed", previousSchool: "North Dakota", newSchool: "South Florida", hometown: "Switzerland", country: "Switzerland", utr: "12.50", classYear: "", dateUpdated: "2026-05-27" },
  { id: "68", name: "Pepijn Bastiaansen", status: "Signed", previousSchool: "Arizona", newSchool: "Mississippi State", hometown: "Netherlands", country: "Netherlands", utr: "12.85", classYear: "", dateUpdated: "2026-05-27" },
  { id: "69", name: "Matthew Forbes", status: "Signed", previousSchool: "Michigan State", newSchool: "Ohio State", hometown: "", country: "", utr: "13.60", classYear: "", dateUpdated: "2026-05-27" },
  { id: "70", name: "Erik Schiessl", status: "Signed", previousSchool: "Florida State", newSchool: "Baylor", hometown: "Germany", country: "Germany", utr: "13.33", classYear: "", dateUpdated: "2026-05-27" },
  { id: "71", name: "Cole Thurgur", status: "Committed", previousSchool: "Rider", newSchool: "Charlotte", hometown: "Canada", country: "Canada", utr: "12.27", classYear: "", dateUpdated: "2026-05-27" },
  { id: "72", name: "Zaid Al Mashni", status: "Committed", previousSchool: "Wichita State", newSchool: "Penn", hometown: "Jordan", country: "Jordan", utr: "12.70", classYear: "", dateUpdated: "2026-05-27" },
  { id: "73", name: "Jules Garot", status: "Signed", previousSchool: "Miami (FL)", newSchool: "FAU", hometown: "Belgium", country: "Belgium", utr: "12.60", classYear: "", dateUpdated: "2026-05-27" },
  { id: "74", name: "Hiiro Sakamoto", status: "Committed", previousSchool: "Troy", newSchool: "Charlotte", hometown: "Japan", country: "Japan", utr: "12.45", classYear: "", dateUpdated: "2026-05-27" },
  { id: "75", name: "Callum Markowitz", status: "Committed", previousSchool: "Vanderbilt", newSchool: "Penn", hometown: "", country: "", utr: "12.69", classYear: "", dateUpdated: "2026-05-27" },
  { id: "76", name: "Jan Sebesta", status: "Committed", previousSchool: "Florida State", newSchool: "Nebraska", hometown: "Switzerland", country: "Switzerland", utr: "12.42", classYear: "", dateUpdated: "2026-05-27" },
  { id: "77", name: "Julian Alonso", status: "Signed", previousSchool: "TCU", newSchool: "Georgia", hometown: "Spain", country: "Spain", utr: "13.27", classYear: "", dateUpdated: "2026-05-27" },
  { id: "78", name: "Edoardo Santoni", status: "Signed", previousSchool: "Georgia Southern", newSchool: "College of Charleston", hometown: "Italy", country: "Italy", utr: "12.19", classYear: "", dateUpdated: "2026-05-27" },
  { id: "79", name: "Piotr Andrzejewski", status: "Committed", previousSchool: "Tulane", newSchool: "Michigan State", hometown: "", country: "", utr: "12.60", classYear: "", dateUpdated: "2026-05-27" },
  { id: "80", name: "Pablo Paternostro", status: "Signed", previousSchool: "FGCU", newSchool: "Mercer", hometown: "", country: "", utr: "12.26", classYear: "", dateUpdated: "2026-05-27" },
  { id: "81", name: "Nico Niox", status: "Signed", previousSchool: "Texas A&M Corpus Christi", newSchool: "Mercer", hometown: "France", country: "France", utr: "11.99", classYear: "", dateUpdated: "2026-05-27" },
  { id: "82", name: "Petar Teodorovic", status: "Committed", previousSchool: "Cornell", newSchool: "SMU", hometown: "Serbia", country: "Serbia", utr: "13.03", classYear: "Gr.", dateUpdated: "2026-05-27" },
  { id: "83", name: "Roman Venger", status: "Signed", previousSchool: "Utah State", newSchool: "FAU", hometown: "Ukraine", country: "Ukraine", utr: "12.75", classYear: "", dateUpdated: "2026-05-27" },
  { id: "84", name: "Bautista Leguizamom", status: "Signed", previousSchool: "Texas Tech", newSchool: "Wichita State", hometown: "Argentina", country: "Argentina", utr: "12.27", classYear: "Fr.", dateUpdated: "2026-05-27" },
  { id: "85", name: "Léonard Tramolay", status: "Signed", previousSchool: "Louisiana-Lafayette", newSchool: "Wichita State", hometown: "France", country: "France", utr: "12.19", classYear: "Jr.", dateUpdated: "2026-05-27" },
  { id: "86", name: "Dmitry Kopilevich", status: "Signed", previousSchool: "Arkansas", newSchool: "ETSU", hometown: "Slovenia", country: "Slovenia", utr: "12.26", classYear: "", dateUpdated: "2026-05-27" },
  { id: "87", name: "Jakub Prachař", status: "Signed", previousSchool: "New Mexico", newSchool: "ETSU", hometown: "Czech Republic", country: "Czech Republic", utr: "12.18", classYear: "", dateUpdated: "2026-05-27" },
  { id: "34", name: "Nikita Sclearenco", status: "In Portal", previousSchool: "North Dakota", newSchool: "", hometown: "Limassol, Cyprus", country: "Cyprus", utr: "10.71", classYear: "Fr.", dateUpdated: "2026-05-27" },
  { id: "35", name: "Ilias Worthington", status: "Committed", previousSchool: "Wichita State", newSchool: "Old Dominion", hometown: "", country: "", utr: "12.50", classYear: "So.", dateUpdated: "2026-05-27" },
  { id: "36", name: "Christian Capuccini", status: "In Portal", previousSchool: "Tennessee Tech", newSchool: "", hometown: "Perugia, Italy", country: "Italy", utr: "10.40", classYear: "Fr.", dateUpdated: "2026-05-27" },
  { id: "37", name: "Walid Ahouda", status: "In Portal", previousSchool: "Louisville", newSchool: "", hometown: "Casablanca, Morocco", country: "Morocco", utr: "13.32", classYear: "", dateUpdated: "2026-05-27" },
  { id: "38", name: "Tomas Quesada", status: "In Portal", previousSchool: "Abilene Christian", newSchool: "", hometown: "Gran Canaria, Canary Islands", country: "Canary Islands", utr: "12.25", classYear: "", dateUpdated: "2026-05-27" },
  { id: "39", name: "Matteo Lataste", status: "In Portal", previousSchool: "Alabama State", newSchool: "", hometown: "Clermont, France", country: "France", utr: "10.91", classYear: "", dateUpdated: "2026-05-27" },
  { id: "40", name: "Izan Orgiles", status: "Signed", previousSchool: "North Alabama", newSchool: "Boise State", hometown: "Elda, Spain", country: "Spain", utr: "12.26", classYear: "", dateUpdated: "2026-05-27" },
  { id: "41", name: "Cem Atlamis", status: "In Portal", previousSchool: "Georgia State", newSchool: "", hometown: "Bursa, Turkey", country: "Turkey", utr: "11.51", classYear: "Jr.", dateUpdated: "2026-05-27" },
  { id: "42", name: "Calin Stirbu", status: "Signed", previousSchool: "LSU", newSchool: "Nebraska", hometown: "Slatina, Romania", country: "Romania", utr: "12.75", classYear: "So.", dateUpdated: "2026-05-27" },
  { id: "43", name: "Noa Tcherniack", status: "Committed", previousSchool: "Northern Arizona", newSchool: "Michigan State", hometown: "Perols, France", country: "France", utr: "12.72", classYear: "R-Fr.", dateUpdated: "2026-05-27" },
  { id: "44", name: "Francisco Landeras", status: "In Portal", previousSchool: "Drake", newSchool: "", hometown: "Overland Park, Kansas", country: "Kansas", utr: "10.43", classYear: "Fr.", dateUpdated: "2026-05-27" },
  { id: "45", name: "James Lorenzetti", status: "In Portal", previousSchool: "Stetson", newSchool: "", hometown: "Milford, Connecticut", country: "Connecticut", utr: "11.87", classYear: "So.", dateUpdated: "2026-05-27" },
  { id: "46", name: "Loan Lestir", status: "In Portal", previousSchool: "Ole Miss", newSchool: "", hometown: "Lille, France", country: "France", utr: "12.93", classYear: "So.", dateUpdated: "2026-05-27" },
  { id: "47", name: "Egor Gorin", status: "In Portal", previousSchool: "Texas A&M", newSchool: "", hometown: "Moscow, Russia", country: "Russia", utr: "11.80", classYear: "Fr.", dateUpdated: "2026-05-27" },
  { id: "48", name: "Majdi Ben Abdelwahed", status: "In Portal", previousSchool: "Morgan State", newSchool: "", hometown: "Kelibia, Tunisia", country: "Tunisia", utr: "10.99", classYear: "So.", dateUpdated: "2026-05-27" },
  { id: "49", name: "Gabriel Garay", status: "Committed", previousSchool: "West Alabama", newSchool: "Troy", hometown: "", country: "", utr: "12.58", classYear: "", dateUpdated: "2026-05-27" },
  { id: "50", name: "Jose Murariu", status: "In Portal", previousSchool: "Southern Miss", newSchool: "", hometown: "Parrish, Florida", country: "Florida", utr: "12.25", classYear: "So.", dateUpdated: "2026-05-27" },
  { id: "51", name: "Joao Barreto", status: "In Portal", previousSchool: "Eastern Kentucky", newSchool: "", hometown: "Portugal", country: "Portugal", utr: "11.77", classYear: "Fr.", dateUpdated: "2026-05-27" },
  { id: "52", name: "Ilie Cazac", status: "In Portal", previousSchool: "Eastern Kentucky", newSchool: "", hometown: "Chișinău, Moldova", country: "Moldova", utr: "11.85", classYear: "Fr.", dateUpdated: "2026-05-27" },
  { id: "53", name: "Connor Dils", status: "In Portal", previousSchool: "New Mexico", newSchool: "", hometown: "Albuquerque, New Mexico", country: "New Mexico", utr: "11.17", classYear: "R-Fr.", dateUpdated: "2026-05-27" },
  { id: "54", name: "Aryan Saleh", status: "Signed", previousSchool: "Old Dominion", newSchool: "MTSU", hometown: "Eschborn, Germany", country: "Germany", utr: "12.69", classYear: "", dateUpdated: "2026-05-27" },
  { id: "55", name: "Eñaut Garcia Beitia", status: "In Portal", previousSchool: "Hofstra", newSchool: "", hometown: "Vitoria-Gasteiz, Spain", country: "Spain", utr: "11.50", classYear: "Jr.", dateUpdated: "2026-05-27" },
  { id: "56", name: "Andrew Lavine", status: "In Portal", previousSchool: "UC Riverside", newSchool: "", hometown: "Austin, Texas", country: "Texas", utr: "11.37", classYear: "Fr.", dateUpdated: "2026-05-27" },
  { id: "57", name: "Harry Abel", status: "In Portal", previousSchool: "UNCW", newSchool: "", hometown: "Yorkshire, England", country: "England", utr: "11.46", classYear: "Fr.", dateUpdated: "2026-05-27" },
  { id: "58", name: "Artem Alekseychuk", status: "In Portal", previousSchool: "UIC", newSchool: "", hometown: "Alicante, Spain", country: "Spain", utr: "12.12", classYear: "", dateUpdated: "2026-05-27" },
  { id: "59", name: "Gus Tettamble", status: "In Portal", previousSchool: "Tulsa", newSchool: "", hometown: "St. Louis, Missouri", country: "Missouri", utr: "12.13", classYear: "Gr.", dateUpdated: "2026-05-27" },
  { id: "60", name: "Michael Kouame", status: "In Portal", previousSchool: "UNLV", newSchool: "", hometown: "Paris, France", country: "France", utr: "12.30", classYear: "So.", dateUpdated: "2026-05-27" },
  { id: "61", name: "Eemil Pasanen", status: "In Portal", previousSchool: "Utah State", newSchool: "", hometown: "Espoo, Finland", country: "Finland", utr: "11.33", classYear: "So.", dateUpdated: "2026-05-27" },
  { id: "21", name: "Marek Nano", status: "Committed", previousSchool: "Eastern Kentucky", newSchool: "St. John's", hometown: "Slovakia", country: "Slovakia", utr: "12.02", classYear: "Fr.", dateUpdated: "2026-05-27" },
  { id: "22", name: "Asier Ayllon Prado", status: "Committed", previousSchool: "UIndy", newSchool: "MTSU", hometown: "Getafe, Spain", country: "Spain", utr: "12.38", classYear: "So.", dateUpdated: "2026-05-27" },
  { id: "23", name: "Nikola Puntarič", status: "Committed", previousSchool: "Northern Illinois", newSchool: "UIC", hometown: "Ljubljana, Slovenia", country: "Slovenia", utr: "12.80", classYear: "So.", dateUpdated: "2026-05-27" },
  { id: "24", name: "Raffi Ymer", status: "Committed", previousSchool: "Elon", newSchool: "Kentucky", hometown: "Sweden", country: "Sweden", utr: "12.67", classYear: "So.", dateUpdated: "2026-05-27" },
  { id: "25", name: "Jakub Volesky", status: "Committed", previousSchool: "Northern Arizona", newSchool: "VCU", hometown: "Czech Republic", country: "Czech Republic", utr: "12.23", classYear: "", dateUpdated: "2026-05-27" },
  { id: "26", name: "Andrew Delgado", status: "Committed", previousSchool: "Wake Forest", newSchool: "Georgia", hometown: "Greensboro, North Carolina", country: "North Carolina", utr: "13.10", classYear: "R-Fr.", dateUpdated: "2026-05-27" },
  { id: "27", name: "Oscar Baumgartner", status: "Committed", previousSchool: "UNCW", newSchool: "St. Joseph's", hometown: "Vevey, Switzerland", country: "Switzerland", utr: "12.10", classYear: "", dateUpdated: "2026-05-27" },
  { id: "28", name: "Setti Germano", status: "Signed", previousSchool: "Midwestern State", newSchool: "DePaul", hometown: "Carazinho, Brazil", country: "Brazil", utr: "12.21", classYear: "", dateUpdated: "2026-05-27" },
  { id: "30", name: "Benjamin Martin", status: "Committed", previousSchool: "Ole Miss", newSchool: "Memphis", hometown: "Nort-sur-Erdre, France", country: "France", utr: "12.88", classYear: "", dateUpdated: "2026-05-27" },
  { id: "31", name: "Sasa Markovic", status: "Committed", previousSchool: "LSU", newSchool: "SMU", hometown: "Loznica, Serbia", country: "Serbia", utr: "13.11", classYear: "So.", dateUpdated: "2026-05-27" },
  { id: "32", name: "Itamar Tapiro", status: "Committed", previousSchool: "Delaware", newSchool: "Coastal Carolina", hometown: "", country: "", utr: "12.05", classYear: "", dateUpdated: "2026-05-27" },
  { id: "33", name: "Matthieu Coignet", status: "In Portal", previousSchool: "Texas A&M Corpus Christi", newSchool: "", hometown: "Clamart, France", country: "France", utr: "11.60", classYear: "", dateUpdated: "2026-05-27" },
  { id: "15", name: "Oskar Grzegorzewski", status: "Committed", previousSchool: "UTSA", newSchool: "UC Santa Barbara", hometown: "Marki, Poland", country: "Poland", utr: "12.56", classYear: "So.", dateUpdated: "2026-05-27" },
  { id: "16", name: "Dragos Nicolae Cazacu", status: "In Portal", previousSchool: "Tennessee", newSchool: "", hometown: "Romania", country: "Romania", utr: "13.28", classYear: "Fr.", dateUpdated: "2026-05-27" },
  { id: "17", name: "Yannic Nittmann", status: "Committed", previousSchool: "Clemson", newSchool: "Memphis", hometown: "Cologne, Germany", country: "Germany", utr: "12.72", classYear: "Fr.", dateUpdated: "2026-05-27" },
  { id: "18", name: "Caleb Saltz", status: "Committed", previousSchool: "Boston College", newSchool: "Miami (FL)", hometown: "Canyon Country, California", country: "California", utr: "12.05", classYear: "Sr.", dateUpdated: "2026-05-27" },
  { id: "19", name: "Filip Apltauer", status: "Committed", previousSchool: "TCU", newSchool: "Florida State", hometown: "Prague, Czech Republic", country: "Czech Republic", utr: "13.11", classYear: "Sr.", dateUpdated: "2026-05-27" },
  { id: "20", name: "Santi Padilla Cote", status: "Committed", previousSchool: "Stetson", newSchool: "Tulane", hometown: "Plantation, Florida", country: "Florida", utr: "12.46", classYear: "So.", dateUpdated: "2026-05-27" },
  { id: "13", name: "Thomas Nelson", status: "Committed", previousSchool: "Old Dominion", newSchool: "Michigan State", hometown: "", country: "", utr: "12.19", classYear: "Jr.", dateUpdated: "2026-05-27" },
  { id: "14", name: "Ashton Adesoro", status: "Signed", previousSchool: "Western Michigan", newSchool: "Miami (FL)", hometown: "", country: "", utr: "12.61", classYear: "Sr.", dateUpdated: "2026-05-27" },
  { id: "12", name: "Hamza Nasridinov", status: "Signed", previousSchool: "Auburn", newSchool: "Texas A&M", hometown: "Nurek, Tajikistan", country: "Tajikistan", utr: "13.56", classYear: "Jr.", dateUpdated: "2026-05-27" },
  { id: "2", name: "Alan Bojarski", status: "Signed", previousSchool: "Auburn", newSchool: "Tennessee", hometown: "Warsaw, Poland", country: "Poland", utr: "13.05", classYear: "Jr.", dateUpdated: "2026-05-27" },
  { id: "10", name: "Oscar Lacides",   status: "Committed",  previousSchool: "Oklahoma",  newSchool: "Tennessee",          hometown: "France", country: "France", utr: "13.61", classYear: "Sr.", dateUpdated: "2026-05-27" },
  { id: "1",  name: "Orel Kihmi",       status: "Committed",  previousSchool: "Oklahoma",   newSchool: "Tennessee",    hometown: "Israel", country: "Israel", utr: "13.63", classYear: "Jr.", dateUpdated: "2026-05-27" },
  { id: "8",  name: "Hank Trondson",       status: "Committed",  previousSchool: "Oklahoma",  newSchool: "Oklahoma State",          hometown: "Nashville, Tennessee", country: "Tennessee", utr: "12.99", classYear: "Jr.", dateUpdated: "2026-05-27" },
  { id: "5",  name: "Jan Kobierski",    status: "Committed",  previousSchool: "Tennessee", newSchool: "San Diego State",   hometown: "", country: "", utr: "12.69", classYear: "Jr.", dateUpdated: "2026-05-27" },
  { id: "9",  name: "Piotr Siekanowicz",     status: "Committed",  previousSchool: "Tennessee",  newSchool: "San Diego State", hometown: "Poland", country: "Poland", utr: "12.57", classYear: "Jr.", dateUpdated: "2026-05-27" },
  { id: "3",  name: "Ariel Zauber",  status: "Committed",     previousSchool: "Wake Forest",     newSchool: "Indiana",       hometown: "", country: "", utr: "12.52", classYear: "Jr.", dateUpdated: "2026-05-27" },
  { id: "7",  name: "Blake Anderson",     status: "Signed",     previousSchool: "Baylor",       newSchool: "San Diego State",  hometown: "", country: "", utr: "12.38", classYear: "So.", dateUpdated: "2026-05-27" },
  { id: "6",  name: "Mats Bredschneijder",     status: "Committed",  previousSchool: "VCU",    newSchool: "Hawaii",          hometown: "", country: "", utr: "12.39", classYear: "Jr.", dateUpdated: "2026-05-27" },
  { id: "11", name: "Arsene Pougault",     status: "Signed",     previousSchool: "Arkansas, Charlotte",  newSchool: "Boise State",   hometown: "France", country: "France", utr: "12.58", classYear: "Jr.", dateUpdated: "2026-05-27" },
  { id: "4",  name: "Nicholas Heng",      status: "Signed",  previousSchool: "Auburn", newSchool: "Michigan",        hometown: "Madison, Alabama", country: "Alabama", utr: "13.27", classYear: "R-Sr.", dateUpdated: "2026-05-27" },
];
